#define ROS_VERSION_ALPHA       1
#define ROS_VERSION_BOXTURTLE   2
#define ROS_VERSION_CTURTLE     3
#define ROS_VERSION_DIAMONDBACK 4
#define ROS_VERSION_ELECTRIC    5
#define ROS_VERSION_FUERTE      6
#define ROS_VERSION_GROOVY      7

#define QUICKDEV_ROS_VERSION ROS_VERSION_GROOVY
