/* auto-generated by genmsg_cpp from /home/kitty/ros/stacks/interaction-ros-pkg/bandit/bandit_actionlib/msg/BanditAction.msg.  Do not edit! */
#ifndef BANDIT_ACTIONLIB_BANDITACTION_H
#define BANDIT_ACTIONLIB_BANDITACTION_H

#include <string>
#include <vector>
#include "ros/message.h"
#include "ros/debug.h"
#include "ros/assert.h"
#include "ros/time.h"

#include "roslib/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "bandit_actionlib/BanditGoal.h"
#include "bandit_actionlib/BanditActionGoal.h"
#include "actionlib_msgs/GoalStatus.h"
#include "bandit_actionlib/BanditResult.h"
#include "bandit_actionlib/BanditActionResult.h"
#include "bandit_actionlib/BanditFeedback.h"
#include "bandit_actionlib/BanditActionFeedback.h"

namespace bandit_actionlib
{

//! \htmlinclude BanditAction.msg.html

class BanditAction : public ros::Message
{
public:
  typedef boost::shared_ptr<BanditAction> Ptr;
  typedef boost::shared_ptr<BanditAction const> ConstPtr;

  typedef bandit_actionlib::BanditActionGoal _action_goal_type;
  typedef bandit_actionlib::BanditActionResult _action_result_type;
  typedef bandit_actionlib::BanditActionFeedback _action_feedback_type;

  bandit_actionlib::BanditActionGoal action_goal;
  bandit_actionlib::BanditActionResult action_result;
  bandit_actionlib::BanditActionFeedback action_feedback;

  BanditAction() : ros::Message()
  {
  }
  BanditAction(const BanditAction &copy) : ros::Message(),
    action_goal(copy.action_goal),
    action_result(copy.action_result),
    action_feedback(copy.action_feedback)
  {
    (void)copy;
  }
  BanditAction &operator =(const BanditAction &copy)
  {
    if (this == &copy)
      return *this;
    action_goal = copy.action_goal;
    action_result = copy.action_result;
    action_feedback = copy.action_feedback;
    return *this;
  }
  virtual ~BanditAction() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("bandit_actionlib/BanditAction"); }
  inline static std::string __s_getMD5Sum() { return std::string("70b130ecb9b4f74981eaded3a71cfa4e"); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "\n"
    "BanditActionGoal action_goal\n"
    "BanditActionResult action_result\n"
    "BanditActionFeedback action_feedback\n"
    "\n"
    "================================================================================\n"
    "MSG: bandit_actionlib/BanditActionGoal\n"
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "\n"
    "Header header\n"
    "actionlib_msgs/GoalID goal_id\n"
    "BanditGoal goal\n"
    "\n"
    "================================================================================\n"
    "MSG: roslib/Header\n"
    "# Standard metadata for higher-level stamped data types.\n"
    "# This is generally used to communicate timestamped data \n"
    "# in a particular coordinate frame.\n"
    "# \n"
    "# sequence ID: consecutively increasing ID \n"
    "uint32 seq\n"
    "#Two-integer timestamp that is expressed as:\n"
    "# * stamp.secs: seconds (stamp_secs) since epoch\n"
    "# * stamp.nsecs: nanoseconds since stamp_secs\n"
    "# time-handling sugar is provided by the client library\n"
    "time stamp\n"
    "#Frame this data is associated with\n"
    "# 0: no frame\n"
    "# 1: global frame\n"
    "string frame_id\n"
    "\n"
    "================================================================================\n"
    "MSG: actionlib_msgs/GoalID\n"
    "# The stamp should store the time at which this goal was requested.\n"
    "# It is used by an action server when it tries to preempt all\n"
    "# goals that were requested before a certain time\n"
    "time stamp\n"
    "\n"
    "# The id provides a way to associate feedback and\n"
    "# result message with specific goal requests. The id\n"
    "# specified must be unique.\n"
    "string id\n"
    "\n"
    "\n"
    "================================================================================\n"
    "MSG: bandit_actionlib/BanditGoal\n"
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "#goal definition\n"
    "string frame\n"
    "\n"
    "================================================================================\n"
    "MSG: bandit_actionlib/BanditActionResult\n"
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "\n"
    "Header header\n"
    "actionlib_msgs/GoalStatus status\n"
    "BanditResult result\n"
    "\n"
    "================================================================================\n"
    "MSG: actionlib_msgs/GoalStatus\n"
    "GoalID goal_id\n"
    "uint8 status\n"
    "uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
    "uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
    "uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
    "                            #   and has since completed its execution (Terminal State)\n"
    "uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
    "uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
    "                            #    to some failure (Terminal State)\n"
    "uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
    "                            #    because the goal was unattainable or invalid (Terminal State)\n"
    "uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
    "                            #    and has not yet completed execution\n"
    "uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
    "                            #    but the action server has not yet confirmed that the goal is canceled\n"
    "uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
    "                            #    and was successfully cancelled (Terminal State)\n"
    "uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
    "                            #    sent over the wire by an action server\n"
    "\n"
    "#Allow for the user to associate a string with GoalStatus for debugging\n"
    "string text\n"
    "\n"
    "\n"
    "================================================================================\n"
    "MSG: bandit_actionlib/BanditResult\n"
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "#result definition\n"
    "int32 total_time\n"
    "float32[] result_joint_id\n"
    "float32[] result_joint_angle\n"
    "\n"
    "================================================================================\n"
    "MSG: bandit_actionlib/BanditActionFeedback\n"
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "\n"
    "Header header\n"
    "actionlib_msgs/GoalStatus status\n"
    "BanditFeedback feedback\n"
    "\n"
    "================================================================================\n"
    "MSG: bandit_actionlib/BanditFeedback\n"
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "#feedback\n"
    "int32 progress_time\n"
    "float32[] progress_joint_id\n"
    "float32[] progress_joint_angle\n"
    "\n"
    "\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    __l += action_goal.serializationLength(); // action_goal
    __l += action_result.serializationLength(); // action_result
    __l += action_feedback.serializationLength(); // action_feedback
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr,
#if defined(__GNUC__)
                             __attribute__((unused)) uint32_t seq) const
#else
                             uint32_t seq) const
#endif
  {
    write_ptr = action_goal.serialize(write_ptr, seq);
    write_ptr = action_result.serialize(write_ptr, seq);
    write_ptr = action_feedback.serialize(write_ptr, seq);
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    read_ptr = action_goal.deserialize(read_ptr);
    read_ptr = action_result.deserialize(read_ptr);
    read_ptr = action_feedback.deserialize(read_ptr);
    return read_ptr;
  }
};

typedef boost::shared_ptr<BanditAction> BanditActionPtr;
typedef boost::shared_ptr<BanditAction const> BanditActionConstPtr;


}

#endif
