JointCalibrations:
- JointID: 0
  Direction: 1
  TrueZero: 28.9863
  Offset: 27
  MaxAngle: 0
  MinAngle: -55.9863
- JointID: 1
  Direction: -1
  TrueZero: 0
  Offset: 0
  MaxAngle: 0
  MinAngle: 0
- JointID: 2
  Direction: 1
  TrueZero: -59.1816
  Offset: -97
  MaxAngle: 0
  MinAngle: -156.182
- JointID: 3
  Direction: 1
  TrueZero: -86.0547
  Offset: 175
  MaxAngle: 88.9453
  MinAngle: 0
- JointID: 4
  Direction: 1
  TrueZero: -93.0957
  Offset: -55
  MaxAngle: 0
  MinAngle: -148.096
- JointID: 5
  Direction: -1
  TrueZero: 77.6387
  Offset: 128
  MaxAngle: 50.3613
  MinAngle: 0
- JointID: 6
  Direction: 1
  TrueZero: -3.85937
  Offset: 77
  MaxAngle: 80.8594
  MinAngle: 0
- JointID: 7
  Direction: 1
  TrueZero: 29.2958
  Offset: 28
  MaxAngle: 57.2958
  MinAngle: 0
- JointID: 8
  Direction: 1
  TrueZero: 0.6
  Offset: 0
  MaxAngle: 0
  MinAngle: 0
- JointID: 9
  Direction: -1
  TrueZero: 39.8125
  Offset: -98
  MaxAngle: 0
  MinAngle: -137.812
- JointID: 10
  Direction: -1
  TrueZero: 78.2422
  Offset: 170
  MaxAngle: 91.7578
  MinAngle: 0
- JointID: 11
  Direction: -1
  TrueZero: 32.5781
  Offset: -120
  MaxAngle: 0
  MinAngle: -152.578
- JointID: 12
  Direction: 1
  TrueZero: -59.0371
  Offset: 121
  MaxAngle: 61.9629
  MinAngle: 0
- JointID: 13
  Direction: -1
  TrueZero: 3.5918
  Offset: 87
  MaxAngle: 83.4082
  MinAngle: 0
- JointID: 14
  Direction: -1
  TrueZero: 29.2958
  Offset: 28
  MaxAngle: 57.2958
  MinAngle: 0
- JointID: 15
  Direction: 1
  TrueZero: 0.5
  Offset: 0
  MaxAngle: 0
  MinAngle: 0
- JointID: 16
  Direction: 1
  TrueZero: 0.2
  Offset: 0
  MaxAngle: 0
  MinAngle: 0
- JointID: 17
  Direction: 1
  TrueZero: 0.25
  Offset: 0
  MaxAngle: 0
  MinAngle: 0
- JointID: 18
  Direction: -1
  TrueZero: 0.25
  Offset: 0
  MaxAngle: 0
  MinAngle: 0
