# autogenerated by genmsg_py from BanditAction.msg. Do not edit.
import roslib.message
import struct

import roslib.rostime
import bandit_actionlib.msg
import roslib.msg
import actionlib_msgs.msg

class BanditAction(roslib.message.Message):
  _md5sum = "52a894a3d9c03f814b99899cbd3ea1db"
  _type = "bandit_actionlib/BanditAction"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

BanditActionGoal action_goal
BanditActionResult action_result
BanditActionFeedback action_feedback

================================================================================
MSG: bandit_actionlib/BanditActionGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
BanditGoal goal

================================================================================
MSG: roslib/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: bandit_actionlib/BanditGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
string frame

================================================================================
MSG: bandit_actionlib/BanditActionResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
BanditResult result

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text


================================================================================
MSG: bandit_actionlib/BanditResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#result definition
float32 total_time
float32[] result_joint_id
float32[] result_joint_angle

================================================================================
MSG: bandit_actionlib/BanditActionFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
BanditFeedback feedback

================================================================================
MSG: bandit_actionlib/BanditFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#feedback
float32 progress_time
float32 progress_hold_time
float32[] progress_joint_id
float32[] progress_joint_angle


"""
  __slots__ = ['action_goal','action_result','action_feedback']
  _slot_types = ['bandit_actionlib/BanditActionGoal','bandit_actionlib/BanditActionResult','bandit_actionlib/BanditActionFeedback']

  ## Constructor. Any message fields that are implicitly/explicitly
  ## set to None will be assigned a default value. The recommend
  ## use is keyword arguments as this is more robust to future message
  ## changes.  You cannot mix in-order arguments and keyword arguments.
  ##
  ## The available fields are:
  ##   action_goal,action_result,action_feedback
  ##
  ## @param self: self
  ## @param args: complete set of field values, in .msg order
  ## @param kwds: use keyword arguments corresponding to message field names
  ## to set specific fields. 
  def __init__(self, *args, **kwds):
    if args or kwds:
      super(BanditAction, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.action_goal is None:
        self.action_goal = bandit_actionlib.msg.BanditActionGoal()
      if self.action_result is None:
        self.action_result = bandit_actionlib.msg.BanditActionResult()
      if self.action_feedback is None:
        self.action_feedback = bandit_actionlib.msg.BanditActionFeedback()
    else:
      self.action_goal = bandit_actionlib.msg.BanditActionGoal()
      self.action_result = bandit_actionlib.msg.BanditActionResult()
      self.action_feedback = bandit_actionlib.msg.BanditActionFeedback()

  ## internal API method
  def _get_types(self): return self._slot_types

  ## serialize message into buffer
  ## @param buff StringIO: buffer
  def serialize(self, buff):
    try:
      buff.write(struct.pack('<3I', self.action_goal.header.seq, self.action_goal.header.stamp.secs, self.action_goal.header.stamp.nsecs))
      length = len(self.action_goal.header.frame_id)
      #serialize self.action_goal.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.action_goal.header.frame_id))
      buff.write(struct.pack('<2I', self.action_goal.goal_id.stamp.secs, self.action_goal.goal_id.stamp.nsecs))
      length = len(self.action_goal.goal_id.id)
      #serialize self.action_goal.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.action_goal.goal_id.id))
      length = len(self.action_goal.goal.frame)
      #serialize self.action_goal.goal.frame
      buff.write(struct.pack('<I%ss'%length, length, self.action_goal.goal.frame))
      buff.write(struct.pack('<3I', self.action_result.header.seq, self.action_result.header.stamp.secs, self.action_result.header.stamp.nsecs))
      length = len(self.action_result.header.frame_id)
      #serialize self.action_result.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.action_result.header.frame_id))
      buff.write(struct.pack('<2I', self.action_result.status.goal_id.stamp.secs, self.action_result.status.goal_id.stamp.nsecs))
      length = len(self.action_result.status.goal_id.id)
      #serialize self.action_result.status.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.action_result.status.goal_id.id))
      buff.write(struct.pack('<B', self.action_result.status.status))
      length = len(self.action_result.status.text)
      #serialize self.action_result.status.text
      buff.write(struct.pack('<I%ss'%length, length, self.action_result.status.text))
      buff.write(struct.pack('<f', self.action_result.result.total_time))
      #serialize self.action_result.result.result_joint_id
      length = len(self.action_result.result.result_joint_id)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.action_result.result.result_joint_id))
      #serialize self.action_result.result.result_joint_angle
      length = len(self.action_result.result.result_joint_angle)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.action_result.result.result_joint_angle))
      buff.write(struct.pack('<3I', self.action_feedback.header.seq, self.action_feedback.header.stamp.secs, self.action_feedback.header.stamp.nsecs))
      length = len(self.action_feedback.header.frame_id)
      #serialize self.action_feedback.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.action_feedback.header.frame_id))
      buff.write(struct.pack('<2I', self.action_feedback.status.goal_id.stamp.secs, self.action_feedback.status.goal_id.stamp.nsecs))
      length = len(self.action_feedback.status.goal_id.id)
      #serialize self.action_feedback.status.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.action_feedback.status.goal_id.id))
      buff.write(struct.pack('<B', self.action_feedback.status.status))
      length = len(self.action_feedback.status.text)
      #serialize self.action_feedback.status.text
      buff.write(struct.pack('<I%ss'%length, length, self.action_feedback.status.text))
      buff.write(struct.pack('<2f', self.action_feedback.feedback.progress_time, self.action_feedback.feedback.progress_hold_time))
      #serialize self.action_feedback.feedback.progress_joint_id
      length = len(self.action_feedback.feedback.progress_joint_id)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.action_feedback.feedback.progress_joint_id))
      #serialize self.action_feedback.feedback.progress_joint_angle
      length = len(self.action_feedback.feedback.progress_joint_angle)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.action_feedback.feedback.progress_joint_angle))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  ## unpack serialized message in str into this message instance
  ## @param self: self
  ## @param str str: byte array of serialized message
  def deserialize(self, str):
    try:
      if self.action_goal is None:
        self.action_goal = bandit_actionlib.msg.BanditActionGoal()
      if self.action_result is None:
        self.action_result = bandit_actionlib.msg.BanditActionResult()
      if self.action_feedback is None:
        self.action_feedback = bandit_actionlib.msg.BanditActionFeedback()
      end = 0
      start = end
      end += 12
      (self.action_goal.header.seq, self.action_goal.header.stamp.secs, self.action_goal.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_goal.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_goal.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_goal.goal_id.stamp.secs, self.action_goal.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_goal.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_goal.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_goal.goal.frame
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_goal.goal.frame,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 12
      (self.action_result.header.seq, self.action_result.header.stamp.secs, self.action_result.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_result.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_result.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_result.status.goal_id.stamp.secs, self.action_result.status.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_result.status.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_result.status.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 1
      (self.action_result.status.status,) = struct.unpack('<B',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_result.status.text
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_result.status.text,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (self.action_result.result.total_time,) = struct.unpack('<f',str[start:end])
      #deserialize self.action_result.result.result_joint_id
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_result.result.result_joint_id = struct.unpack(pattern, str[start:end])
      #deserialize self.action_result.result.result_joint_angle
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_result.result.result_joint_angle = struct.unpack(pattern, str[start:end])
      start = end
      end += 12
      (self.action_feedback.header.seq, self.action_feedback.header.stamp.secs, self.action_feedback.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_feedback.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_feedback.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_feedback.status.goal_id.stamp.secs, self.action_feedback.status.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_feedback.status.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_feedback.status.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 1
      (self.action_feedback.status.status,) = struct.unpack('<B',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_feedback.status.text
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_feedback.status.text,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_feedback.feedback.progress_time, self.action_feedback.feedback.progress_hold_time,) = struct.unpack('<2f',str[start:end])
      #deserialize self.action_feedback.feedback.progress_joint_id
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_feedback.feedback.progress_joint_id = struct.unpack(pattern, str[start:end])
      #deserialize self.action_feedback.feedback.progress_joint_angle
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_feedback.feedback.progress_joint_angle = struct.unpack(pattern, str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  ## serialize message with numpy array types into buffer
  ## @param self: self
  ## @param buff StringIO: buffer
  ## @param numpy module: numpy python module
  def serialize_numpy(self, buff, numpy):
    try:
      buff.write(struct.pack('<3I', self.action_goal.header.seq, self.action_goal.header.stamp.secs, self.action_goal.header.stamp.nsecs))
      length = len(self.action_goal.header.frame_id)
      #serialize self.action_goal.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.action_goal.header.frame_id))
      buff.write(struct.pack('<2I', self.action_goal.goal_id.stamp.secs, self.action_goal.goal_id.stamp.nsecs))
      length = len(self.action_goal.goal_id.id)
      #serialize self.action_goal.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.action_goal.goal_id.id))
      length = len(self.action_goal.goal.frame)
      #serialize self.action_goal.goal.frame
      buff.write(struct.pack('<I%ss'%length, length, self.action_goal.goal.frame))
      buff.write(struct.pack('<3I', self.action_result.header.seq, self.action_result.header.stamp.secs, self.action_result.header.stamp.nsecs))
      length = len(self.action_result.header.frame_id)
      #serialize self.action_result.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.action_result.header.frame_id))
      buff.write(struct.pack('<2I', self.action_result.status.goal_id.stamp.secs, self.action_result.status.goal_id.stamp.nsecs))
      length = len(self.action_result.status.goal_id.id)
      #serialize self.action_result.status.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.action_result.status.goal_id.id))
      buff.write(struct.pack('<B', self.action_result.status.status))
      length = len(self.action_result.status.text)
      #serialize self.action_result.status.text
      buff.write(struct.pack('<I%ss'%length, length, self.action_result.status.text))
      buff.write(struct.pack('<f', self.action_result.result.total_time))
      #serialize self.action_result.result.result_joint_id
      length = len(self.action_result.result.result_joint_id)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(self.action_result.result.result_joint_id.tostring())
      #serialize self.action_result.result.result_joint_angle
      length = len(self.action_result.result.result_joint_angle)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(self.action_result.result.result_joint_angle.tostring())
      buff.write(struct.pack('<3I', self.action_feedback.header.seq, self.action_feedback.header.stamp.secs, self.action_feedback.header.stamp.nsecs))
      length = len(self.action_feedback.header.frame_id)
      #serialize self.action_feedback.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.action_feedback.header.frame_id))
      buff.write(struct.pack('<2I', self.action_feedback.status.goal_id.stamp.secs, self.action_feedback.status.goal_id.stamp.nsecs))
      length = len(self.action_feedback.status.goal_id.id)
      #serialize self.action_feedback.status.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.action_feedback.status.goal_id.id))
      buff.write(struct.pack('<B', self.action_feedback.status.status))
      length = len(self.action_feedback.status.text)
      #serialize self.action_feedback.status.text
      buff.write(struct.pack('<I%ss'%length, length, self.action_feedback.status.text))
      buff.write(struct.pack('<2f', self.action_feedback.feedback.progress_time, self.action_feedback.feedback.progress_hold_time))
      #serialize self.action_feedback.feedback.progress_joint_id
      length = len(self.action_feedback.feedback.progress_joint_id)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(self.action_feedback.feedback.progress_joint_id.tostring())
      #serialize self.action_feedback.feedback.progress_joint_angle
      length = len(self.action_feedback.feedback.progress_joint_angle)
      buff.write(struct.pack('<I', length))
      pattern = '<%sf'%length
      buff.write(self.action_feedback.feedback.progress_joint_angle.tostring())
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  ## unpack serialized message in str into this message instance using numpy for array types
  ## @param self: self
  ## @param str str: byte array of serialized message
  ## @param numpy module: numpy python module
  def deserialize_numpy(self, str, numpy):
    try:
      if self.action_goal is None:
        self.action_goal = bandit_actionlib.msg.BanditActionGoal()
      if self.action_result is None:
        self.action_result = bandit_actionlib.msg.BanditActionResult()
      if self.action_feedback is None:
        self.action_feedback = bandit_actionlib.msg.BanditActionFeedback()
      end = 0
      start = end
      end += 12
      (self.action_goal.header.seq, self.action_goal.header.stamp.secs, self.action_goal.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_goal.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_goal.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_goal.goal_id.stamp.secs, self.action_goal.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_goal.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_goal.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_goal.goal.frame
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_goal.goal.frame,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 12
      (self.action_result.header.seq, self.action_result.header.stamp.secs, self.action_result.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_result.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_result.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_result.status.goal_id.stamp.secs, self.action_result.status.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_result.status.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_result.status.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 1
      (self.action_result.status.status,) = struct.unpack('<B',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_result.status.text
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_result.status.text,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (self.action_result.result.total_time,) = struct.unpack('<f',str[start:end])
      #deserialize self.action_result.result.result_joint_id
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_result.result.result_joint_id = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      #deserialize self.action_result.result.result_joint_angle
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_result.result.result_joint_angle = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 12
      (self.action_feedback.header.seq, self.action_feedback.header.stamp.secs, self.action_feedback.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_feedback.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_feedback.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_feedback.status.goal_id.stamp.secs, self.action_feedback.status.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_feedback.status.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_feedback.status.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 1
      (self.action_feedback.status.status,) = struct.unpack('<B',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.action_feedback.status.text
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.action_feedback.status.text,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.action_feedback.feedback.progress_time, self.action_feedback.feedback.progress_hold_time,) = struct.unpack('<2f',str[start:end])
      #deserialize self.action_feedback.feedback.progress_joint_id
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_feedback.feedback.progress_joint_id = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      #deserialize self.action_feedback.feedback.progress_joint_angle
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.action_feedback.feedback.progress_joint_angle = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

